# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ElectrodeOffsetDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(49, 29, 251, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.mVLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.mVLayout.setContentsMargins(0, 0, 0, 0)
        self.mVLayout.setObjectName("mVLayout")
        self.dataFormLayout = QtWidgets.QFormLayout()
        self.dataFormLayout.setContentsMargins(5, 5, 5, 5)
        self.dataFormLayout.setObjectName("dataFormLayout")
        self.mVLayout.addLayout(self.dataFormLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.mVLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
